services:
  mindloom:
    build: .
    ports:
      - "8330:8000"
    volumes:
      - "/mnt/Movies-And-More/Documents/Writing/Obsidian Vault:/vault"
      - ./data:/app/data
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CALENDAR_ICS_PATH=${CALENDAR_ICS_PATH}
      - TIME_ZONE=${TIME_ZONE}
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID}
      - GOOGLE_CREDENTIALS_PATH=${GOOGLE_CREDENTIALS_PATH}
    command: sh -c "python parse_projects.py && uvicorn main:app --host 0.0.0.0 --port 8000"
