services:
  mindloom:
    build: .
    ports:
      - "8330:8000"
    volumes:
      - "/mnt/Movies-And-More/Documents/Writing/Obsidian Vault:/vault"
      - ./data:/app/data
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PORT=8000
    command: sh -c "python parse_projects.py && uvicorn main:app --host 0.0.0.0 --port 8000"
