name: Black

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black==25.1.0
    - name: Check code formatting
      run: |
        black --check $(git ls-files '*.py')
